bookmarks/bookmarks/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^',include('account.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^images/', include('images.urls', namespace = 'images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
	url(r'^$',views.image_list,name="list"),
	
	url(r'^create/$',
		views.ImageCreateView.as_view(),
		name = "create"),

	url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
		views.ImageDetailView.as_view(),
		name = "detail"),

	url(r'^like/$',
		views.ImageLikeView.as_view(),
		name = "like"),
]

bookmarks/images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.core.urlresolvers import reverse

class Image(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,
							related_name = 'images_created')
	title = models.CharField(max_length = 200)
	slug = models.SlugField(max_length = 200,
							blank = True)
	url = models.URLField()
	image = models.ImageField(upload_to = 'images/%Y/%m/%d')
	description = models.TextField(blank = True)
	created = models.DateField(auto_now_add = True,
								db_index = True)
	user_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
										related_name='images_liked',
										blank=True)
	total_likes = models.PositiveIntegerField(db_index = True, default=0)

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.title)
		super(Image, self).save(*args, **kwargs)

	def get_absolute_url(self):
		return reverse('images:detail',args=[self.id, self.slug])

bookmarks/images/forms.py
from django import forms
from django.utils.text import slugify
from django.core.files.base import ContentFile
from .models import Image
from urllib import request


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {
            'url': forms.HiddenInput,
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpeg', 'jpg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL doesn\'t'
                                        'matching valid image extensions.')
        return url

    def save(self, force_insert=False,
             force_update=False,
             commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title),
                                    image_url.rsplit('.', 1)[1].lower())
        response = request.urlopen(image_url)
        
        #ContentFile works on string/bytes rather than File object
        image.image.save(image_name,
                         ContentFile(response.read()),
                         save=False)
        if commit:
            image.save()
        return image

bookmarks/images/views.py
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import FormView
from django.views.generic import DetailView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_POST
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import redis
from common.decorators import ajax_required
from actions.utils import create_action
from .forms import ImageCreateForm
from .models import Image

r = redis.StrictRedis(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB)

@method_decorator(login_required, name='dispatch')
class ImageCreateView(FormView):
    form_class = ImageCreateForm
    template_name = 'images/image/create.html'

    def get_initial(self):
        initial = super(ImageCreateView, self).get_initial()
        initial['url'] = self.request.GET.get('url', "")
        initial['title'] = self.request.GET.get('title', "")
        return initial

    def form_valid(self, form):
        new_item = form.save(commit=False)
        new_item.user = self.request.user
        new_item.save()
        create_action(self.request.user, 'bookmarked image', new_item)
        messages.success(self.request, 'Image added successfully')
        return redirect(new_item.get_absolute_url())

    def get_context_data(self, **kwargs):
        context = super(ImageCreateView, self).get_context_data(**kwargs)
        context['section'] = 'images'
        return context


class ImageDetailView(DetailView):
    template_name = "images/image/detail.html"
    context_object_name = "image"
    pk_url_kwargs = "id"
    slug_url_kwargs = "slug"
    model = Image

    def get_queryset(self):
        queryset = Image.objects.filter(
            pk=self.kwargs['id'], slug=self.kwargs['slug'])
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ImageDetailView, self).get_context_data(**kwargs)
        total_views = r.incr('image:{}:views'.format(self.get_object().id))
        context['section'] = 'images'
        context['total_views'] = total_views
        return context


@method_decorator([login_required, ajax_required, require_POST], name='dispatch')
class ImageLikeView(View):
    def post(self, request, *args, **kwargs):
        image_id = request.POST.get('id')
        action = request.POST.get('action')
        if image_id and action:
            image = get_object_or_404(Image, pk=image_id)
            if action == 'like':
                image.user_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.user_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        return JsonResponse({'status': 'ko'})

def image_list(request):
    images = Image.objects.filter(user=request.user)
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer return the first page
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # if the request is AJAX and page is out of range
            # return the empty page
            return HttpResponse('')
        # if page is out of delivery last page of result
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                      'images/image/list_ajax.html',
                      {'images': images})
    return render(request,
                  'images/image/list.html',
                  {'section': 'images', 'images': images})

bookmarks/images/templates/images/image/create.html
{% extends "base.html" %}

{% block title %}Bookmark an image{% endblock %}

{% block content %}
	<h1>Bookmark an Image</h1>
	<img src="{{request.GET.url}}" class="image-preview">
	<form action="." method="post">
		{{ form.as_p }}
		{% csrf_token %}
		<input type="submit" value="Bookmark it!">
	</form>
{% endblock %}

bookmarks/images/templates/images/image/detail.html
{% extends "base.html" %}

{% block title %}{{image.title}}{% endblock %}

{% block domready %}
	$('a.like').click(function(event){
		event.preventDefault();
		$.post({
			url:'{% url 'images:like' %}',
			data:{
				id:$(this).data('id'),
				action:$(this).data('action')
			},
			dataType: 'json',
			success:function(data){
				if (data['status']=='ok'){
					prev_action = $('a.like').data('action');
					//togle data-action
					$('a.like').data('action',prev_action=='like'?'unlike':'like');
					//toggle inner text
					$('a.like').text(prev_action=='like'?'Unlike':'Like');
					//update total likes
					prev_likes = parseInt($('#likes_count').text());
					$('#likes_count').text(prev_action == 'like'?prev_likes+1:prev_likes-1);
				}
			}
		});
	});

{% endblock %}

{% block content %}
	<h1>{{ image.title }}</h1>
	{% load thumbnail %}
	{% thumbnail image.image "300x300" as im %}
		<a  href="{{ image.image.url }}">
			<img src="{{ im.url}}" class="image-detail">
		</a>
	{% endthumbnail %}

	{% with total_likes=image.user_like.count  users_like=image.user_like.all%}
		<div class="image-info">
			<div>
				<span class="count">
					<span class="total" id="likes_count">{{total_likes}}</span> 
					like{{total_likes|pluralize}}
				</span>
				<span class="count">
					<span class="total">{{ total_views }}</span>
					view{{total_views|pluralize}}
				</span>
				<a href="#" data-id="{{image.id}}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
				{% if request.user not in users_like %}
					Like
				{% else %}
					Unlike
				{% endif %}
				</a>
			</div>
			{{ image.description|linebreaks }}
		</div>
		<div class="image-likes">
			{% for user in image.user_like.all %}
				<div>
					<img src="{{user.profile.photo.url}}">
					<p>{{ user.first_name }}</p>
				</div>
			{% empty %}
				Nobody likes it yet!
			{% endfor %}
		</div>
	{% endwith %}
{% endblock %}

bookmarks/images/templates/images/image/list.html
{% extends "base.html" %}

{% block title %} Images Bookmarked {% endblock %}

{% block domready %}
	var page = 1;
	var empty_page = false;
	var block_request = false;
	$(window).scroll(function(){
		var margin = $(document).height() - $(window).height()-200;
		if($(window).scrollTop() > margin && empty_page == false && block_request == false){
			block_request = true;
			page += 1;
			$.get('?page='+page,function(data){
				if(data == ''){
					empty_page = true;
				}else{
					block_request = false;
					$('#image-list').append(data);
				}
			});
		}

	});
{% endblock %}

{% block content %}
	<h1> Images Bookmarked </h1>
	<div id="image-list">
		{% include "images/image/list_ajax.html" %}
	</div>
{% endblock %}

bookmarks/images/templates/images/image/list_ajax.html
{% load thumbnail %}

{% for image in images %}
	<div class="image">
		<a href="{{image.get_absolute_url}}">
			{% thumbnail image.image "300x300" crop="100%" as im %}
				<a href="{{ image.get_absolute_url }}">
					<img src="{{ im.url }}">
				</a>
			{% endthumbnail %}
		</a>
		<div class="info">
			<a href="{{ image.get_absolute_url }}" class="title">
				{{ image.title }}
			</a>
		</div>
	</div>
{% endfor %}