bookmarks/bookmarks/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^',include('account.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^images/', include('images.urls', namespace = 'images')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
	url(r'^$',views.image_list,name="list"),
	
	url(r'^create/$',
		views.ImageCreateView.as_view(),
		name = "create"),

	url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
		views.ImageDetailView.as_view(),
		name = "detail"),

	url(r'^like/$',
		views.ImageLikeView.as_view(),
		name = "like"),
]

bookmarks/templates/base.html
{% load staticfiles %}
<! DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	<link href='{% static "css/base.css" %}' rel="stylesheet">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
	<script>
		$(function(){
			$("ul.messages .close").click(function(){
				$("ul.messages").hide();
			});
		});
	</script>
	<script>
		var csrftoken = $.cookie('csrftoken');
		function csrfSafeMethods(method){
			//these methods are safe and don't require token
			//Here we are doing pattern matching
			return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
		}
		//setting for future ajax requests
		$.ajaxSetup({
			beforeSend:function(xhr, settings){
				if(!csrfSafeMethods(settings.type) && !this.crossDomain){
					xhr.setRequestHeader("X-CSRFToken",csrftoken);
				}
			}
		});
		$(document).ready(function(){
			{% block domready %}
			{% endblock %}
		});
	</script>

</head>
<body>
	<div id="header">
		<span class="logo">Bookmarks</span>
		{% if request.user.is_authenticated %}
			<ul class= "menu">
				<li {% if section == 'dashboard' %}class="selected"{% endif %}>
					<a href="{% url 'dashboard' %}">My Dashboard </a>
				</li>
				<li {% if section == 'images' %}class="selected"{% endif %}>
					<a href="{% url 'images:list' %}"> Images </a>
				</li>
				<li {% if section == "people" %}class="selected"{% endif %}>
					<a href="{% url "user_list" %}">People</a>
				</li>
			</ul>
		{% endif %}

		<span class = "user">
			{% if request.user.is_authenticated %}
				Hello {{request.user.first_name}} |
				<a href="{% url 'password_change' %}">Change Password</a> |
				<a href="{% url 'edit' %}">Edit Profile</a>|
				<a href="{% url 'logout' %}">Logout</a>
			{% else %}
				<a href="{% url 'register' %}">Register</a> |
				<a href="{% url 'login' %}">Log-in</a>
			{% endif %}
		</span>

	</div>
	{% if messages %}
		<ul class="messages">
			{% for message in messages %}
				<li class="{{message.tags}}">
					{{message|safe}}
					<a href="#" class="close">x</a>
				</li>
			{% endfor %}
		</ul>
	{% endif %}
	
	<div id="content">
		{% block content %}
		{% endblock %}
	</div>
</body>
</html>